### ISSUE TITLE
several replication connections

### ISSUE THREAD

**Issue by krombel** [turt2live/synapse-netcore-workers#40]
I get this log (followed by a crash) which makes me think, that the reconnect is done several times in parallel:

How running: In docker
Which version: 1a5b550355b3a5486698e35cbb3604c620857096

<details><summary>Logs of federation_worker</summary>
<p>

```
19-03-11 22:40:46.762 INF Matrix.SynapseInterop.Replication.SynapseReplication {} Sending FEDERATION_ACK 147550                                                                                                                   
19-03-11 22:40:46.825 INF Matrix.SynapseInterop.Replication.SynapseReplication {} Reconnecting to replication: Attempt 2
19-03-11 22:40:46.825 INF Matrix.SynapseInterop.Replication.SynapseReplication {} Lost replication connection - reconnecting
19-03-11 22:40:46.825 ERR Matrix.SynapseInterop.Replication.SynapseReplication {} Failed to read from replication: System.ObjectDisposedException: Cannot access a disposed object.                                              
Object name: 'System.Net.Sockets.NetworkStream'.
   at System.Net.Sockets.NetworkStream.get_DataAvailable()                                                                                                                                                                       
   at Matrix.SynapseInterop.Replication.SynapseReplication.ReadLoop() in /app/Matrix.SynapseInterop.Replication/SynapseReplication.cs:line 132                                                                                   
19-03-11 22:40:46.826 INF Matrix.SynapseInterop.Replication.SynapseReplication {} Reconnecting to replication: Attempt 1                                                                                                         
19-03-11 22:40:46.826 INF Matrix.SynapseInterop.Replication.SynapseReplication {} Lost replication connection - reconnecting                                                                                                     
19-03-11 22:40:46.826 INF Matrix.SynapseInterop.Replication.SynapseReplication {} Connecting to replication stream on 127.0.0.1:9092                                                                                             
19-03-11 22:40:46.826 ERR Matrix.SynapseInterop.Replication.SynapseReplication {} Failed to read from replication: System.ObjectDisposedException: Cannot access a disposed object.                                              
Object name: 'System.Net.Sockets.NetworkStream'.                                                                                                                                                                                 
   at System.Net.Sockets.NetworkStream.get_DataAvailable()
   at Matrix.SynapseInterop.Replication.SynapseReplication.ReadLoop() in /app/Matrix.SynapseInterop.Replication/SynapseReplication.cs:line 132                                                                                   
19-03-11 22:40:46.827 INF Matrix.SynapseInterop.Replication.SynapseReplication {} Reconnecting to replication: Attempt 1                                                                                                         
19-03-11 22:40:46.827 INF Matrix.SynapseInterop.Replication.SynapseReplication {} Lost replication connection - reconnecting                                                                                                     
19-03-11 22:40:46.827 INF Matrix.SynapseInterop.Replication.SynapseReplication {} Reconnecting to replication: Attempt 2                                                                                                         
19-03-11 22:40:46.827 INF Matrix.SynapseInterop.Replication.SynapseReplication {} Lost replication connection - reconnecting                                                                                                     
19-03-11 22:40:46.828 INF Matrix.SynapseInterop.Replication.SynapseReplication {} Reconnecting to replication: Attempt 2                                                                                                         
19-03-11 22:40:46.828 INF Matrix.SynapseInterop.Replication.SynapseReplication {} Lost replication connection - reconnecting
19-03-11 22:40:46.831 INF Matrix.SynapseInterop.Replication.SynapseReplication {} Connecting to replication stream on 127.0.0.1:9092                                                                                             
19-03-11 22:40:46.831 INF Matrix.SynapseInterop.Replication.SynapseReplication {} Connecting to replication stream on 127.0.0.1:9092                                                                                             
19-03-11 22:40:46.831 INF Matrix.SynapseInterop.Replication.SynapseReplication {} Connecting to replication stream on 127.0.0.1:9092                                                                                             
19-03-11 22:40:46.831 INF Matrix.SynapseInterop.Replication.SynapseReplication {} Sending NAME NetCoreFederationWorker                                                                                                           
19-03-11 22:40:46.831 INF Matrix.SynapseInterop.Replication.SynapseReplication {} Sending REPLICATE federation 147551                                                                                                            
19-03-11 22:40:46.831 INF Matrix.SynapseInterop.Replication.SynapseReplication {} Sending REPLICATE events 1677958                                                                                                               
19-03-11 22:40:46.839 INF Matrix.SynapseInterop.Replication.SynapseReplication {} Sending FEDERATION_ACK 147551
19-03-11 22:40:46.848 ERR Matrix.SynapseInterop.Replication.SynapseReplication {} Reconnection failed: System.Net.Sockets.SocketException (22): Invalid argument                                                                 
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)                                                                                                              
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.InternalBind(EndPoint localEP)
   at System.Net.Sockets.Socket.BeginConnectEx(EndPoint remoteEP, Boolean flowContext, AsyncCallback callback, Object state)                                                                                                     
   at System.Net.Sockets.Socket.UnsafeBeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state, Boolean flowContext)                                                                                                 
   at System.Net.Sockets.Socket.BeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state)
   at System.Net.Sockets.Socket.BeginConnect(IPAddress address, Int32 port, AsyncCallback requestCallback, Object state)                                                                                                         
   at System.Net.Sockets.TcpClient.BeginConnect(IPAddress address, Int32 port, AsyncCallback requestCallback, Object state)                                                                                                      
   at System.Net.Sockets.TcpClient.<>c.<ConnectAsync>b__27_0(IPAddress targetAddess, Int32 targetPort, AsyncCallback callback, Object state)                                                                                     
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2](Func`5 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)                     
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state)                                                                                    
   at System.Net.Sockets.TcpClient.ConnectAsync(IPAddress address, Int32 port)
   at Matrix.SynapseInterop.Replication.SynapseReplication.Reconnect(Boolean firstAttempt) in /app/Matrix.SynapseInterop.Replication/SynapseReplication.cs:line 78
   at Matrix.SynapseInterop.Replication.SynapseReplication.ReconnectLoop() in /app/Matrix.SynapseInterop.Replication/SynapseReplication.cs:line 106
19-03-11 22:40:46.849 INF Matrix.SynapseInterop.Replication.SynapseReplication {} Connecting to replication stream on 127.0.0.1:9092
19-03-11 22:40:46.865 INF Matrix.SynapseInterop.Replication.SynapseReplication {} Sending PING -8586492628386117982
19-03-11 22:40:46.883 INF Matrix.SynapseInterop.Replication.SynapseReplication {} Sending FEDERATION_ACK 147552
```

</p>
</details>

<details><summary>This is the corresponding server-side</summary>
<p>

```
2019-03-11 23:40:40,828 - synapse.replication.tcp.resource - 181 - INFO - replication_notifier-188857 - Streaming: typing -> 13264
2019-03-11 23:40:40,928 - synapse.replication.tcp.protocol - 327 - INFO -  - [NetCoreFederationWorker-sjIul] Resume producing
2019-03-11 23:40:40,969 - synapse.replication.tcp.protocol - 311 - ERROR - replication-ERROR-2 - [NetCoreFederationWorker-sjIul] Remote reported error: 'Error processing incoming commands'
2019-03-11 23:40:40,970 - synapse.replication.tcp.protocol - 153 - INFO -  - [anon-SmnhB] Connection established
2019-03-11 23:40:40,975 - synapse.replication.tcp.protocol - 335 - INFO -  - [NetCoreFederationWorker-sjIul] Stop producing
2019-03-11 23:40:40,976 - synapse.replication.tcp.protocol - 358 - INFO -  - [NetCoreFederationWorker-sjIul] Connection was closed
2019-03-11 23:40:40,976 - synapse.replication.tcp.protocol - 339 - INFO -  - [NetCoreFederationWorker-sjIul] Replication connection closed: <twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>
2019-03-11 23:40:40,977 - synapse.replication.tcp.protocol - 358 - INFO -  - [NetCoreFederationWorker-sjIul] Connection was closed
2019-03-11 23:40:40,978 - synapse.replication.tcp.protocol - 407 - INFO - replication-NAME-30 - [anon-SmnhB] Renamed to 'NetCoreFederationWorker'
2019-03-11 23:40:41,011 - synapse.replication.tcp.protocol - 321 - INFO - replication-REPLICATE-federation-23 - [NetCoreFederationWorker-SmnhB] Pause producing
2019-03-11 23:40:41,016 - synapse.replication.tcp.protocol - 327 - INFO -  - [NetCoreFederationWorker-SmnhB] Resume producing
2019-03-11 23:40:41,064 - synapse.replication.tcp.protocol - 311 - ERROR - replication-ERROR-3 - [NetCoreFederationWorker-SmnhB] Remote reported error: 'Error processing incoming commands'
2019-03-11 23:40:41,066 - synapse.replication.tcp.protocol - 335 - INFO -  - [NetCoreFederationWorker-SmnhB] Stop producing
2019-03-11 23:40:41,067 - synapse.replication.tcp.protocol - 358 - INFO -  - [NetCoreFederationWorker-SmnhB] Connection was closed
2019-03-11 23:40:41,069 - synapse.replication.tcp.protocol - 339 - INFO -  - [NetCoreFederationWorker-SmnhB] Replication connection closed: <twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>
2019-03-11 23:40:41,069 - synapse.replication.tcp.protocol - 358 - INFO -  - [NetCoreFederationWorker-SmnhB] Connection was closed
2019-03-11 23:40:41,072 - synapse.replication.tcp.protocol - 153 - INFO -  - [anon-WlTrx] Connection established
2019-03-11 23:40:41,073 - synapse.replication.tcp.protocol - 153 - INFO -  - [anon-egZjN] Connection established
2019-03-11 23:40:41,074 - synapse.replication.tcp.protocol - 407 - INFO - replication-NAME-31 - [anon-WlTrx] Renamed to 'NetCoreFederationWorker'
2019-03-11 23:40:41,141 - synapse.replication.tcp.protocol - 321 - INFO - replication-REPLICATE-federation-24 - [NetCoreFederationWorker-WlTrx] Pause producing
2019-03-11 23:40:41,145 - synapse.replication.tcp.protocol - 311 - ERROR - replication-ERROR-4 - [NetCoreFederationWorker-WlTrx] Remote reported error: 'Error processing incoming commands'
2019-03-11 23:40:41,151 - synapse.replication.tcp.protocol - 153 - INFO -  - [anon-ipMNk] Connection established
2019-03-11 23:40:41,152 - synapse.replication.tcp.protocol - 335 - INFO -  - [NetCoreFederationWorker-WlTrx] Stop producing
2019-03-11 23:40:41,152 - synapse.replication.tcp.protocol - 358 - INFO -  - [NetCoreFederationWorker-WlTrx] Connection was closed
2019-03-11 23:40:41,153 - synapse.replication.tcp.protocol - 339 - INFO -  - [NetCoreFederationWorker-WlTrx] Replication connection closed: <twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>
2019-03-11 23:40:41,154 - synapse.replication.tcp.protocol - 358 - INFO -  - [NetCoreFederationWorker-WlTrx] Connection was closed
2019-03-11 23:40:41,154 - synapse.replication.tcp.protocol - 407 - INFO - replication-NAME-32 - [anon-egZjN] Renamed to 'NetCoreFederationWorker'
2019-03-11 23:40:41,187 - synapse.replication.tcp.protocol - 321 - INFO - replication-REPLICATE-federation-25 - [NetCoreFederationWorker-egZjN] Pause producing
2019-03-11 23:40:41,198 - synapse.replication.tcp.protocol - 153 - INFO -  - [anon-TdJda] Connection established
2019-03-11 23:40:41,199 - synapse.replication.tcp.protocol - 153 - INFO -  - [anon-UJnGd] Connection established
2019-03-11 23:40:41,199 - synapse.replication.tcp.protocol - 153 - INFO -  - [anon-LOasY] Connection established
2019-03-11 23:40:41,199 - synapse.replication.tcp.protocol - 153 - INFO -  - [anon-WjYUn] Connection established
2019-03-11 23:40:41,200 - synapse.replication.tcp.protocol - 153 - INFO -  - [anon-UNHzz] Connection established
2019-03-11 23:40:41,200 - synapse.replication.tcp.protocol - 153 - INFO -  - [anon-uzYEd] Connection established
2019-03-11 23:40:41,201 - synapse.replication.tcp.protocol - 153 - INFO -  - [anon-ClMXN] Connection established
2019-03-11 23:40:41,201 - synapse.replication.tcp.protocol - 153 - INFO -  - [anon-sKNYJ] Connection established
2019-03-11 23:40:41,202 - synapse.replication.tcp.protocol - 335 - INFO -  - [NetCoreFederationWorker-egZjN] Stop producing
2019-03-11 23:40:41,202 - synapse.replication.tcp.protocol - 358 - INFO -  - [NetCoreFederationWorker-egZjN] Connection was closed
2019-03-11 23:40:41,203 - synapse.replication.tcp.protocol - 339 - INFO -  - [NetCoreFederationWorker-egZjN] Replication connection closed: <twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>
2019-03-11 23:40:41,203 - synapse.replication.tcp.protocol - 358 - INFO -  - [NetCoreFederationWorker-egZjN] Connection was closed
2019-03-11 23:40:41,205 - synapse.replication.tcp.protocol - 407 - INFO - replication-NAME-33 - [anon-ipMNk] Renamed to 'NetCoreFederationWorker'
2019-03-11 23:40:41,242 - synapse.replication.tcp.protocol - 321 - INFO - replication-REPLICATE-federation-26 - [NetCoreFederationWorker-ipMNk] Pause producing
2019-03-11 23:40:41,246 - synapse.replication.tcp.protocol - 327 - INFO -  - [NetCoreFederationWorker-ipMNk] Resume producing
2019-03-11 23:40:41,280 - synapse.replication.tcp.protocol - 335 - INFO -  - [anon-TdJda] Stop producing
2019-03-11 23:40:41,281 - synapse.replication.tcp.protocol - 358 - INFO -  - [anon-TdJda] Connection was closed
2019-03-11 23:40:41,282 - synapse.replication.tcp.protocol - 339 - INFO -  - [anon-TdJda] Replication connection closed: <twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>
2019-03-11 23:40:41,283 - synapse.replication.tcp.protocol - 358 - INFO -  - [anon-TdJda] Connection was closed
2019-03-11 23:40:41,283 - synapse.replication.tcp.protocol - 407 - INFO - replication-NAME-34 - [anon-LOasY] Renamed to 'NetCoreFederationWorker'
2019-03-11 23:40:41,284 - synapse.replication.tcp.protocol - 407 - INFO - replication-NAME-35 - [NetCoreFederationWorker-LOasY] Renamed to 'NetCoreFederationWorker'
2019-03-11 23:40:41,312 - synapse.replication.tcp.protocol - 321 - INFO - replication-REPLICATE-federation-27 - [NetCoreFederationWorker-LOasY] Pause producing
2019-03-11 23:40:41,324 - synapse.replication.tcp.protocol - 407 - INFO - replication-NAME-36 - [anon-WjYUn] Renamed to 'NetCoreFederationWorker'
2019-03-11 23:40:41,360 - synapse.replication.tcp.protocol - 321 - INFO - replication-REPLICATE-federation-29 - [NetCoreFederationWorker-WjYUn] Pause producing
2019-03-11 23:40:41,364 - synapse.replication.tcp.protocol - 407 - INFO - replication-NAME-37 - [anon-uzYEd] Renamed to 'NetCoreFederationWorker'
2019-03-11 23:40:41,394 - synapse.replication.tcp.protocol - 321 - INFO - replication-REPLICATE-federation-30 - [NetCoreFederationWorker-uzYEd] Pause producing
2019-03-11 23:40:41,397 - synapse.replication.tcp.protocol - 407 - INFO - replication-NAME-38 - [anon-ClMXN] Renamed to 'NetCoreFederationWorker'
2019-03-11 23:40:41,429 - synapse.replication.tcp.protocol - 321 - INFO - replication-REPLICATE-federation-31 - [NetCoreFederationWorker-ClMXN] Pause producing
2019-03-11 23:40:41,432 - synapse.replication.tcp.protocol - 327 - INFO -  - [NetCoreFederationWorker-ClMXN] Resume producing
2019-03-11 23:40:41,448 - synapse.replication.tcp.protocol - 407 - INFO - replication-NAME-39 - [anon-sKNYJ] Renamed to 'NetCoreFederationWorker'
2019-03-11 23:40:41,480 - synapse.replication.tcp.protocol - 321 - INFO - replication-REPLICATE-federation-32 - [NetCoreFederationWorker-sKNYJ] Pause producing
2019-03-11 23:40:41,491 - synapse.replication.tcp.protocol - 327 - INFO -  - [NetCoreFederationWorker-sKNYJ] Resume producing
2019-03-11 23:40:41,575 - synapse.replication.tcp.protocol - 335 - INFO -  - [NetCoreFederationWorker-LOasY] Stop producing
2019-03-11 23:40:41,575 - synapse.replication.tcp.protocol - 358 - INFO -  - [NetCoreFederationWorker-LOasY] Connection was closed
2019-03-11 23:40:41,578 - synapse.replication.tcp.protocol - 339 - INFO -  - [NetCoreFederationWorker-LOasY] Replication connection closed: <twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>
2019-03-11 23:40:41,578 - synapse.replication.tcp.protocol - 358 - INFO -  - [NetCoreFederationWorker-LOasY] Connection was closed
2019-03-11 23:40:41,578 - synapse.replication.tcp.protocol - 335 - INFO -  - [NetCoreFederationWorker-WjYUn] Stop producing
2019-03-11 23:40:41,579 - synapse.replication.tcp.protocol - 358 - INFO -  - [NetCoreFederationWorker-WjYUn] Connection was closed
2019-03-11 23:40:41,579 - synapse.replication.tcp.protocol - 339 - INFO -  - [NetCoreFederationWorker-WjYUn] Replication connection closed: <twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>
2019-03-11 23:40:41,580 - synapse.replication.tcp.protocol - 358 - INFO -  - [NetCoreFederationWorker-WjYUn] Connection was closed
2019-03-11 23:40:41,580 - synapse.replication.tcp.protocol - 335 - INFO -  - [NetCoreFederationWorker-uzYEd] Stop producing
2019-03-11 23:40:41,580 - synapse.replication.tcp.protocol - 358 - INFO -  - [NetCoreFederationWorker-uzYEd] Connection was closed
2019-03-11 23:40:41,581 - synapse.replication.tcp.protocol - 339 - INFO -  - [NetCoreFederationWorker-uzYEd] Replication connection closed: <twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>
2019-03-11 23:40:41,581 - synapse.replication.tcp.protocol - 358 - INFO -  - [NetCoreFederationWorker-uzYEd] Connection was closed
2019-03-11 23:40:42,630 - synapse.replication.tcp.resource - 181 - INFO - replication_notifier-188858 - Streaming: receipts -> 2251855
2019-03-11 23:40:48,764 - synapse.replication.tcp.protocol - 153 - INFO -  - [anon-NexFL] Connection established
2019-03-11 23:40:48,765 - synapse.replication.tcp.protocol - 153 - INFO -  - [anon-nDWwJ] Connection established
2019-03-11 23:40:48,766 - synapse.replication.tcp.protocol - 153 - INFO -  - [anon-EatUu] Connection established
2019-03-11 23:40:48,766 - synapse.replication.tcp.protocol - 153 - INFO -  - [anon-nWzkC] Connection established
2019-03-11 23:40:48,766 - synapse.replication.tcp.protocol - 153 - INFO -  - [anon-cQxuw] Connection established
2019-03-11 23:40:48,767 - synapse.replication.tcp.protocol - 153 - INFO -  - [anon-TaYKx] Connection established
2019-03-11 23:40:48,767 - synapse.replication.tcp.protocol - 153 - INFO -  - [anon-TCkWW] Connection established
2019-03-11 23:40:48,811 - synapse.replication.tcp.protocol - 335 - INFO -  - [NetCoreFederationWorker-sKNYJ] Stop producing
2019-03-11 23:40:48,811 - synapse.replication.tcp.protocol - 358 - INFO -  - [NetCoreFederationWorker-sKNYJ] Connection was closed
2019-03-11 23:40:48,812 - synapse.replication.tcp.protocol - 339 - INFO -  - [NetCoreFederationWorker-sKNYJ] Replication connection closed: <twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>
2019-03-11 23:40:48,812 - synapse.replication.tcp.protocol - 358 - INFO -  - [NetCoreFederationWorker-sKNYJ] Connection was closed
2019-03-11 23:40:48,822 - synapse.replication.tcp.protocol - 335 - INFO -  - [anon-NexFL] Stop producing
2019-03-11 23:40:48,822 - synapse.replication.tcp.protocol - 358 - INFO -  - [anon-NexFL] Connection was closed
2019-03-11 23:40:48,822 - synapse.replication.tcp.protocol - 339 - INFO -  - [anon-NexFL] Replication connection closed: <twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>
2019-03-11 23:40:48,823 - synapse.replication.tcp.protocol - 358 - INFO -  - [anon-NexFL] Connection was closed
2019-03-11 23:40:48,824 - synapse.replication.tcp.protocol - 407 - INFO - replication-NAME-40 - [anon-EatUu] Renamed to 'NetCoreFederationWorker'
2019-03-11 23:40:48,837 - synapse.replication.tcp.protocol - 335 - INFO -  - [anon-nWzkC] Stop producing
2019-03-11 23:40:48,838 - synapse.replication.tcp.protocol - 358 - INFO -  - [anon-nWzkC] Connection was closed
2019-03-11 23:40:48,838 - synapse.replication.tcp.protocol - 339 - INFO -  - [anon-nWzkC] Replication connection closed: <twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>
2019-03-11 23:40:48,838 - synapse.replication.tcp.protocol - 358 - INFO -  - [anon-nWzkC] Connection was closed
2019-03-11 23:40:48,839 - synapse.replication.tcp.protocol - 407 - INFO - replication-NAME-41 - [anon-cQxuw] Renamed to 'NetCoreFederationWorker'
2019-03-11 23:40:48,852 - synapse.replication.tcp.protocol - 407 - INFO - replication-NAME-42 - [anon-TCkWW] Renamed to 'NetCoreFederationWorker'
2019-03-11 23:40:48,853 - synapse.replication.tcp.protocol - 407 - INFO - replication-NAME-43 - [NetCoreFederationWorker-TCkWW] Renamed to 'NetCoreFederationWorker'
2019-03-11 23:40:49,279 - synapse.replication.tcp.protocol - 335 - INFO -  - [NetCoreFederationWorker-cQxuw] Stop producing
2019-03-11 23:40:49,279 - synapse.replication.tcp.protocol - 358 - INFO -  - [NetCoreFederationWorker-cQxuw] Connection was closed
2019-03-11 23:40:49,280 - synapse.replication.tcp.protocol - 339 - INFO -  - [NetCoreFederationWorker-cQxuw] Replication connection closed: <twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>
2019-03-11 23:40:49,280 - synapse.replication.tcp.protocol - 358 - INFO -  - [NetCoreFederationWorker-cQxuw] Connection was closed
2019-03-11 23:40:49,727 - synapse.replication.tcp.resource - 181 - INFO - replication_notifier-188859 - Streaming: presence -> 55017722
2019-03-11 23:40:51,048 - synapse.replication.tcp.resource - 181 - INFO - replication_notifier-188860 - Streaming: presence -> 55017723
2019-03-11 23:40:54,481 - synapse.replication.tcp.resource - 181 - INFO - replication_notifier-188861 - Streaming: presence -> 55017724
2019-03-11 23:40:54,842 - synapse.replication.tcp.resource - 181 - INFO - replication_notifier-188862 - Streaming: presence -> 55017725
2019-03-11 23:40:55,283 - synapse.replication.tcp.resource - 181 - INFO - replication_notifier-188862 - Streaming: presence -> 55017727
2019-03-11 23:40:55,478 - synapse.replication.tcp.resource - 181 - INFO - replication_notifier-188863 - Streaming: presence -> 55017728
2019-03-11 23:40:56,265 - synapse.replication.tcp.resource - 181 - INFO - replication_notifier-188864 - Streaming: presence -> 55017729
2019-03-11 23:40:57,632 - synapse.replication.tcp.resource - 181 - INFO - replication_notifier-188865 - Streaming: presence -> 55017730
2019-03-11 23:40:57,638 - synapse.replication.tcp.resource - 181 - INFO - replication_notifier-188865 - Streaming: events -> 1677959
2019-03-11 23:41:00,613 - synapse.replication.tcp.resource - 181 - INFO - replication_notifier-188866 - Streaming: presence -> 55017731
2019-03-11 23:41:00,647 - synapse.replication.tcp.resource - 181 - INFO - replication_notifier-188866 - Streaming: receipts -> 2251856
2019-03-11 23:41:00,828 - synapse.replication.tcp.resource - 181 - INFO - replication_notifier-188868 - Streaming: presence -> 55017732
2019-03-11 23:41:07,048 - synapse.replication.tcp.protocol - 189 - INFO -  - [NetCoreFederationWorker-ClMXN] Connection hasn't received command in 25617 ms. Closing.
2019-03-11 23:41:07,049 - synapse.replication.tcp.protocol - 236 - WARNING -  - [NetCoreFederationWorker-ClMXN] Closing connection
2019-03-11 23:41:07,049 - synapse.replication.tcp.protocol - 358 - INFO -  - [NetCoreFederationWorker-ClMXN] Connection was closed
2019-03-11 23:41:07,104 - synapse.replication.tcp.protocol - 339 - INFO -  - [NetCoreFederationWorker-ClMXN] Replication connection closed: <twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>
2019-03-11 23:41:07,104 - synapse.replication.tcp.protocol - 358 - INFO -  - [NetCoreFederationWorker-ClMXN] Connection was closed
2019-03-11 23:41:07,340 - synapse.replication.tcp.resource - 181 - INFO - replication_notifier-188869 - Streaming: presence -> 55017733
2019-03-11 23:41:07,476 - synapse.replication.tcp.resource - 181 - INFO - replication_notifier-188869 - Streaming: presence -> 55017734
2019-03-11 23:41:07,477 - synapse.replication.tcp.resource - 181 - INFO - replication_notifier-188869 - Streaming: typing -> 13265
2019-03-11 23:41:08,971 - synapse.replication.tcp.resource - 181 - INFO - replication_notifier-188870 - Streaming: presence -> 55017735
2019-03-11 23:41:11,064 - synapse.replication.tcp.resource - 181 - INFO - replication_notifier-188871 - Streaming: presence -> 55017736
2019-03-11 23:41:11,416 - synapse.replication.tcp.protocol - 335 - INFO -  - [NetCoreFederationWorker-EatUu] Stop producing
2019-03-11 23:41:11,416 - synapse.replication.tcp.protocol - 358 - INFO -  - [NetCoreFederationWorker-EatUu] Connection was closed
2019-03-11 23:41:11,417 - synapse.replication.tcp.protocol - 339 - INFO -  - [NetCoreFederationWorker-EatUu] Replication connection closed: <twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.>
2019-03-11 23:41:11,417 - synapse.replication.tcp.protocol - 358 - INFO -  - [NetCoreFederationWorker-EatUu] Connection was closed
2019-03-11 23:41:11,418 - synapse.replication.tcp.protocol - 335 - INFO -  - [NetCoreFederationWorker-TCkWW] Stop producing
2019-03-11 23:41:11,418 - synapse.replication.tcp.protocol - 358 - INFO -  - [NetCoreFederationWorker-TCkWW] Connection was closed
2019-03-11 23:41:11,419 - synapse.replication.tcp.protocol - 339 - INFO -  - [NetCoreFederationWorker-TCkWW] Replication connection closed: <twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.>
2019-03-11 23:41:11,419 - synapse.replication.tcp.protocol - 358 - INFO -  - [NetCoreFederationWorker-TCkWW] Connection was closed
2019-03-11 23:41:11,420 - synapse.replication.tcp.protocol - 335 - INFO -  - [anon-nDWwJ] Stop producing
2019-03-11 23:41:11,420 - synapse.replication.tcp.protocol - 358 - INFO -  - [anon-nDWwJ] Connection was closed
2019-03-11 23:41:11,420 - synapse.replication.tcp.protocol - 339 - INFO -  - [anon-nDWwJ] Replication connection closed: <twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.>
2019-03-11 23:41:11,421 - synapse.replication.tcp.protocol - 358 - INFO -  - [anon-nDWwJ] Connection was closed
2019-03-11 23:41:11,423 - synapse.replication.tcp.protocol - 335 - INFO -  - [anon-UNHzz] Stop producing
2019-03-11 23:41:11,423 - synapse.replication.tcp.protocol - 358 - INFO -  - [anon-UNHzz] Connection was closed
2019-03-11 23:41:11,424 - synapse.replication.tcp.protocol - 339 - INFO -  - [anon-UNHzz] Replication connection closed: <twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.>
2019-03-11 23:41:11,424 - synapse.replication.tcp.protocol - 358 - INFO -  - [anon-UNHzz] Connection was closed
2019-03-11 23:41:11,425 - synapse.replication.tcp.protocol - 335 - INFO -  - [anon-UJnGd] Stop producing
2019-03-11 23:41:11,425 - synapse.replication.tcp.protocol - 358 - INFO -  - [anon-UJnGd] Connection was closed
2019-03-11 23:41:11,431 - synapse.replication.tcp.protocol - 339 - INFO -  - [anon-UJnGd] Replication connection closed: <twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.>
2019-03-11 23:41:11,432 - synapse.replication.tcp.protocol - 358 - INFO -  - [anon-UJnGd] Connection was closed
2019-03-11 23:41:11,434 - synapse.replication.tcp.protocol - 335 - INFO -  - [anon-TaYKx] Stop producing
2019-03-11 23:41:11,434 - synapse.replication.tcp.protocol - 358 - INFO -  - [anon-TaYKx] Connection was closed
2019-03-11 23:41:11,435 - synapse.replication.tcp.protocol - 339 - INFO -  - [anon-TaYKx] Replication connection closed: <twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.>
2019-03-11 23:41:11,435 - synapse.replication.tcp.protocol - 358 - INFO -  - [anon-TaYKx] Connection was closed
2019-03-11 23:41:11,436 - synapse.replication.tcp.protocol - 335 - INFO -  - [NetCoreFederationWorker-ipMNk] Stop producing
2019-03-11 23:41:11,436 - synapse.replication.tcp.protocol - 358 - INFO -  - [NetCoreFederationWorker-ipMNk] Connection was closed
2019-03-11 23:41:11,437 - synapse.replication.tcp.protocol - 339 - INFO -  - [NetCoreFederationWorker-ipMNk] Replication connection closed: <twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.>
2019-03-11 23:41:11,437 - synapse.replication.tcp.protocol - 358 - INFO -  - [NetCoreFederationWorker-ipMNk] Connection was closed
```

</p>
</details>

**Comment by turt2live** [comment]
from the synapse side:
```
2019-03-11 09:50:49,379 - synapse.replication.tcp.protocol - 189 - INFO -  - [NetCoreFederationWorker-DKyVZ] Connection hasn't received command in 27080 ms. Closing.
2019-03-11 09:50:49,380 - synapse.replication.tcp.protocol - 236 - WARNING -  - [NetCoreFederationWorker-DKyVZ] Closing connection
2019-03-11 09:50:49,380 - synapse.replication.tcp.protocol - 358 - INFO -  - [NetCoreFederationWorker-DKyVZ] Connection was closed
```

Seems to indicate that the stream is somehow getting stuck in a mode where the .net side thinks it's all on fire and synapse is just watching it burn.

**Comment by Half-Shot** [comment]
@krombel was right, we were not awaiting the reconnect loop at all. See https://github.com/turt2live/synapse-netcore-workers/commit/691bb87d306510242d6ddff38f12499375b9291d
