### ISSUE TITLE
crash through synapse disconnected connection

### ISSUE THREAD

**Issue by krombel** [turt2live/synapse-netcore-workers#41]
How running: in docker
Which version: 1a5b550355b3a5486698e35cbb3604c620857096

<details><summary>Logs of federation_sender</summary>
<p>

```
19-03-11 08:50:52.294 INF Matrix.SynapseInterop.Replication.SynapseReplication {} Sending PING -8586493126331834799                                                                                  
19-03-11 08:50:53.634 INF Matrix.SynapseInterop.Replication.SynapseReplication {} Reconnecting to replication: Attempt 1                                                                             
19-03-11 08:50:53.635 INF Matrix.SynapseInterop.Replication.SynapseReplication {} Lost replication connection - reconnecting                                                                         

19-03-11 08:50:54.071 INF Matrix.SynapseInterop.Replication.SynapseReplication {} Connecting to replication stream on 127.0.0.1:9092                                                                 
19-03-11 08:50:54.147 INF Matrix.SynapseInterop.Replication.SynapseReplication {} Sending NAME NetCoreFederationWorker                                                                               
19-03-11 08:50:54.148 INF Matrix.SynapseInterop.Replication.SynapseReplication {} Sending PING -8586493126313291625                                                                                  
19-03-11 08:50:54.148 INF Matrix.SynapseInterop.Replication.SynapseReplication {} Sending REPLICATE federation 95541                                                                                 
19-03-11 08:50:54.148 INF Matrix.SynapseInterop.Replication.SynapseReplication {} Sending REPLICATE events 1674686                                                                                   
Unhandled Exception: System.Exception: Failed to send command to Synapse ---> System.Net.Sockets.SocketException: Broken pipe                                                                        
   at Matrix.SynapseInterop.Replication.SynapseReplication.SendRaw(String command) in /app/Matrix.SynapseInterop.Replication/SynapseReplication.cs:line 208                                          
   --- End of inner exception stack trace ---
   at Matrix.SynapseInterop.Replication.SynapseReplication.SendRaw(String command) in /app/Matrix.SynapseInterop.Replication/SynapseReplication.cs:line 218                                          
   at Matrix.SynapseInterop.Replication.SynapseReplication.SendPing(Object context) in /app/Matrix.SynapseInterop.Replication/SynapseReplication.cs:line 225                                         
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)                                                                       
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
```

</p>
</details>

<details><summary>Logs on synapse (this is for first connection. The reconnected one behaves similarly)</summary>
<p>

```
2019-03-11 09:50:49,379 - synapse.replication.tcp.protocol - 189 - INFO -  - [NetCoreFederationWorker-DKyVZ] Connection hasn't received command in 27080 ms. Closing.
2019-03-11 09:50:49,380 - synapse.replication.tcp.protocol - 236 - WARNING -  - [NetCoreFederationWorker-DKyVZ] Closing connection
2019-03-11 09:50:49,380 - synapse.replication.tcp.protocol - 358 - INFO -  - [NetCoreFederationWorker-DKyVZ] Connection was closed
```

</p></details>

**Comment by Half-Shot** [comment]
```
19-03-14 14:34:28.358 INF Matrix.SynapseInterop.Replication.SynapseReplication {} Sending PING -8586490328171193084
19-03-14 14:34:28.376 INF Matrix.SynapseInterop.Replication.SynapseReplication {} Reconnecting to replication: Attempt 1
19-03-14 14:34:28.377 INF Matrix.SynapseInterop.Replication.SynapseReplication {} Lost replication connection - reconnecting
19-03-14 14:34:28.379 INF Matrix.SynapseInterop.Replication.SynapseReplication {} Connecting to replication stream on 127.0.0.1:9592
19-03-14 14:34:28.379 INF Matrix.SynapseInterop.Replication.SynapseReplication {} Sending NAME NetCoreFederationWorker
19-03-14 14:34:28.380 INF Matrix.SynapseInterop.Replication.SynapseReplication {} Sending PING -8586490328170968377
19-03-14 14:34:28.381 INF Matrix.SynapseInterop.Replication.SynapseReplication {} Sending REPLICATE federation 990412
19-03-14 14:34:28.381 INF Matrix.SynapseInterop.Replication.SynapseReplication {} Sending REPLICATE events 13779359

Unhandled Exception: System.Exception: Failed to send command to Synapse ---> System.Net.Sockets.SocketException: Broken pipe
   at Matrix.SynapseInterop.Replication.SynapseReplication.SendRaw(String command) in /app/Matrix.SynapseInterop.Replication/SynapseReplication.cs:line 208
   --- End of inner exception stack trace ---
   at Matrix.SynapseInterop.Replication.SynapseReplication.SendRaw(String command) in /app/Matrix.SynapseInterop.Replication/SynapseReplication.cs:line 218
   at Matrix.SynapseInterop.Replication.SynapseReplication.SendPing(Object context) in /app/Matrix.SynapseInterop.Replication/SynapseReplication.cs:line 225
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
Aborted (core dumped)
```

Got the same issue just now.

**Comment by Half-Shot** [comment]
Fixed by https://github.com/turt2live/synapse-netcore-workers/commit/691bb87d306510242d6ddff38f12499375b9291d
